## Imports

In [106]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from io import StringIO
import re

## Data Ingestion

In [2]:
# AP Poll Data - This dataset contains the scores of previous tournament games. Every two rows is a game.

poll_data = pd.read_csv("data/AP Poll Data.csv")

In [3]:
# Ingestion Check
poll_data.head()

,YEAR,WEEK,TEAM NO,TEAM,SEED,ROUND,W,L,AP VOTES,AP RANK,RANK?
0,2026,1,1173.0,Purdue,2.0,0.0,0.0,0.0,1485.0,1.0,1
1,2026,1,1199.0,Houston,2.0,0.0,0.0,0.0,1459.0,2.0,1
2,2026,1,1206.0,Florida,1.0,0.0,0.0,0.0,1382.0,3.0,1
3,2026,1,1208.0,Connecticut,2.0,0.0,0.0,0.0,1299.0,4.0,1
4,2026,1,1165.0,St. John's,5.0,0.0,0.0,0.0,1203.0,5.0,1

In [4]:
# Barttovrik Away-Neutral - This dataset contains the Barttorvik team data for away and neutral games. Team's away and neutral games only count towards this data.

bartt_awaynetural = pd.read_csv("data/Barttorvik Away-Neutral.csv")

In [5]:
# Ingestion Check
bartt_awaynetural.head()

,YEAR,TEAM NO,TEAM ID,TEAM,SEED,ROUND,BADJ EM,BADJ O,BADJ D,BARTHAG,...,BADJT RANK,AVG HGT RANK,EFF HGT RANK,EXP RANK,TALENT RANK,FT% RANK,OP FT% RANK,PPPO RANK,PPPD RANK,ELITE SOS RANK
0,2026,1215,2,Akron,12,0,12.8,116.2,103.4,0.793,...,77,362,363,38,164,220,207,14,51,262
1,2026,1214,3,Alabama,4,0,25.4,127.5,102.1,0.928,...,3,89,76,294,8,28,67,8,209,21
2,2026,1213,8,Arizona,1,0,34.9,127.8,92.9,0.975,...,71,8,26,324,9,188,192,15,31,7
3,2026,1212,10,Arkansas,4,0,23.6,125.5,101.9,0.917,...,30,30,49,309,6,230,298,22,276,4
4,2026,1211,25,BYU,6,0,21.3,123.1,101.8,0.899,...,45,70,98,307,48,103,41,39,113,51

In [6]:
# Coach Results - This dataset contains the tournament results for head coaches since 2008. 
coach_results = pd.read_csv("data/Coach Results.csv")

In [7]:
# Ingestion Check
coach_results.head()

,COACH ID,COACH,PAKE,PAKE RANK,PASE,PASE RANK,GAMES,W,L,WIN%,R64,R32,S16,E8,F4,F2,CHAMP,TOP2,F4%,CHAMP%
0,1,Tom Izzo,8.8,1,10.3,1,51,35,16,0.686,16,14,10,6,4,1,0,5,88.60%,35.50%
1,2,John Calipari,7.6,3,9.8,2,55,41,14,0.745,15,13,11,8,5,3,1,8,99.00%,75.00%
2,3,Brad Stevens,6.5,4,7.6,3,17,12,5,0.706,5,4,2,2,2,2,0,0,25.50%,3.70%
3,4,Dana Altman,6.0,5,6.5,4,26,17,9,0.654,9,9,5,2,1,0,0,1,44.20%,8.30%
4,5,John Beilein,5.5,7,6.5,5,28,19,9,0.679,9,7,5,3,2,2,0,2,65.90%,21.50%

In [8]:
# Conference Results - This dataset contains the tournament results for conferences since 2008. 
conference_results = pd.read_csv("data/Conference Results.csv")

In [9]:
# Ingestion Check
conference_results.head()

,CONF ID,CONF,PAKE,PAKE RANK,PASE,PASE RANK,GAMES,W,L,WIN%,R64,R32,S16,E8,F4,F2,CHAMP,TOP2,CHAMP%
0,2,ACC,15.2,1,10.2,1,255,161,94,0.631,99,66,44,26,13,7,5,28,96.40%
1,14,Horz,5.9,4,7.9,2,31,13,18,0.419,18,5,2,2,2,2,0,0,3.70%
2,28,SEC,6.6,2,7.5,3,228,134,94,0.588,96,59,37,23,10,3,2,18,92.30%
3,24,P12,6.1,3,7.3,4,146,83,63,0.568,63,44,27,9,3,0,0,9,66.50%
4,6,B10,2.2,8,5.9,5,271,159,112,0.587,112,84,43,17,10,5,0,21,93.00%

In [10]:
# Conference Stats Away Neutral - This dataset contains the Barttorvik Conference data for away and neutral games. Conference teams' away and neutral games only count towards this data. All of the statistics below are an average of all teams in a conference, except for G, W, and L as those are cumulative statistics. 
conference_stats = pd.read_csv("data/Conference Stats Away Neutral.csv")

In [11]:
# Ingestion Check
conference_stats.head()

,YEAR,CONF ID,CONF,BADJ EM,BADJ O,BADJ D,BARTHAG,G,W,L,...,AVG HGT,EFF HGT,EXP,TALENT,FT%,OP FT%,PPPO,PPPD,ELITE SOS,WAB
0,2026,1,A10,4.2,109.9,105.7,0.610,222,94,128,...,77.320,80.480,2.050,17.554,71.4,71.7,1.055,1.095,26.390,-3.50
1,2026,2,ACC,16.6,118.2,101.6,0.851,271,122,149,...,78.069,81.107,1.798,55.261,71.3,73.7,1.094,1.111,47.966,0.29
2,2026,3,AE,-15.6,99.5,115.1,0.158,162,42,120,...,76.993,80.087,1.703,6.229,69.6,71.6,0.991,1.128,13.937,-10.00
3,2026,4,Amer,2.0,109.4,107.4,0.553,210,94,116,...,77.342,80.448,1.951,24.405,72.4,72.4,1.059,1.106,23.642,-3.90
4,2026,5,ASun,-10.1,104.9,115.0,0.258,219,63,156,...,77.215,80.117,1.743,7.524,71.8,73.0,1.055,1.176,18.774,-8.70

In [12]:
# Heat Check Ratings - Heat Check CBB’s Ratings are a set of advanced team ratings used to evaluate and project how teams might perform in the NCAA Tournament. 
heat_check_ratings = pd.read_csv("data/Heat Check Ratings.csv")

In [13]:
# Ingestion Check
heat_check_ratings.head()

,YEAR,TEAM NO,TEAM,SEED,ROUND,EASY DRAW,TOUGH DRAW,DARK HORSE,UPSET ALERT,CINDERELLA
0,2026,1188,Louisville,6,0,False,False,True,False,False
1,2026,1163,Tennessee,6,0,False,False,True,False,False
2,2025,1135,Connecticut,8,32,False,False,True,False,False
3,2025,1103,Oklahoma,9,64,False,True,False,False,False
4,2025,1115,Memphis,5,64,False,True,False,True,False

In [14]:
# Heat Check Tournament Index - Heat Check CBB’s Tournament Index are a set of advanced team ratings used to evaluate and project how teams might perform in the NCAA Tournament. 
heat_check_index = pd.read_csv("data/Heat Check Tournament Index.csv")

In [15]:
# Ingestion Check
heat_check_index.head()

,YEAR,TEAM NO,TEAM,SEED,ROUND,POWER,PATH,DRAW,WINS,POOL VALUE,POOL S-RANK,NCAA S-RANK,VAL Z-SCORE,POWER-PATH
0,2026,1215,Akron,12,0,63.2,83.4,NaN,NaN,2.4,47,48,NaN,-20.2
1,2026,1214,Alabama,4,0,84.4,72.4,NaN,NaN,32.3,13,14,NaN,12.0
2,2026,1213,Arizona,1,0,94.0,66.1,NaN,NaN,84.6,2,2,NaN,27.9
3,2026,1212,Arkansas,4,0,82.5,67.8,NaN,NaN,45.9,10,16,NaN,14.7
4,2026,1211,BYU,6,0,78.3,72.9,NaN,NaN,16.7,23,24,NaN,5.4

In [16]:
# Resumes - This dataset contains the resume data for tournament teams. 
resumes = pd.read_csv("data/Resumes.csv")

In [17]:
# Ingestion Check
resumes.head()

,YEAR,TEAM NO,TEAM,SEED,ROUND,NET RPI,RESUME,WAB RANK,ELO,B POWER,Q1 W,Q2 W,Q1 PLUS Q2 W,Q3 Q4 L,PLUS 500,R SCORE,BID TYPE
0,2026,1215,Akron,12,0,53,114,53,27,70.7,0,0,0,1,23,0.91,Auto
1,2026,1214,Alabama,4,0,18,14,14,23,16.7,7,9,16,0,15,99.45,At-Large
2,2026,1213,Arizona,1,0,3,3,3,2,3.0,16,8,24,0,31,99.98,Auto
3,2026,1212,Arkansas,4,0,16,17,15,11,19.0,8,8,16,0,19,99.51,Auto
4,2026,1211,BYU,6,0,22,21,22,38,24.7,7,8,15,0,12,98.40,At-Large

In [18]:
# Seed Results - This dataset contains the tournament results for seeds since 2008. 
seed_results = pd.read_csv("data/Seed Results.csv")

In [19]:
# Ingestion Check
seed_results.head()

,SEED,PAKE,PAKE RANK,PASE,PASE RANK,GAMES,W,L,WIN%,R64,R32,S16,E8,F4,F2,CHAMP,TOP2,CHAMP%
0,11,14.2,2,14.8,1,127,59,68,0.465,68,33,16,6,4,0,0,0,11.80%
1,15,3.8,5,5.2,2,80,12,68,0.150,68,7,4,1,0,0,0,0,0.00%
2,3,5.9,3,4.0,3,196,129,67,0.658,68,60,40,20,5,3,1,0,80.70%
3,4,2.5,6,3.8,4,177,110,67,0.621,68,53,37,11,6,2,1,0,75.80%
4,8,-0.3,8,3.0,5,119,51,68,0.429,68,35,7,3,3,3,0,0,16.30%

In [20]:
# Shooting Splits - This dataset contains the shooting split data for the tournament teams. 
shooting_splits = pd.read_csv("data/Shooting Splits.csv")

In [21]:
# Ingestion Check
shooting_splits.head()

,YEAR,TEAM NO,TEAM ID,TEAM,CONF,DUNKS FG%,DUNKS SHARE,DUNKS FG%D,DUNKS D SHARE,CLOSE TWOS FG%,...,CLOSE TWOS FG%D RANK,CLOSE TWOS D SHARE RANK,FARTHER TWOS FG% RANK,FARTHER TWOS SHARE RANK,FARTHER TWOS FG%D RANK,FARTHER TWOS D SHARE RANK,THREES FG% RANK,THREES SHARE RANK,THREES FG%D RANK,THREES D SHARE RANK
0,2026,1215,2,Akron,MAC,93.1,7.9,87.0,4.2,65.0,...,67,159,22,57,50,295,14,65,256,305
1,2026,1214,3,Alabama,SEC,85.9,10.1,92.7,7.6,61.4,...,86,152,17,14,145,34,72,1,160,52
2,2026,1213,8,Arizona,B12,93.4,9.0,91.4,6.1,64.1,...,19,8,31,345,86,2,62,363,46,109
3,2026,1212,10,Arkansas,SEC,92.0,15.4,87.1,9.8,67.1,...,291,224,307,227,177,174,8,311,56,144
4,2026,1211,25,BYU,B12,84.2,10.4,81.2,8.0,66.9,...,296,14,44,292,153,8,130,174,266,177

In [22]:
# Team Results - This dataset contains the tournament results for teams since 2008. 
team_results = pd.read_csv("data/Team Results.csv")

In [23]:
# Ingestion Check
team_results.head()

,TEAM ID,TEAM,PAKE,PAKE RANK,PASE,PASE RANK,GAMES,W,L,WIN%,R64,R32,S16,E8,F4,F2,CHAMP,TOP2,F4%,CHAMP%
0,1,Abilene Christian,0.7,53,0.7,55,3,1,2,0.333,2,1,0,0,0,0,0,0,0.10%,0.00%
1,2,Akron,-1.2,201,-1.5,208,6,0,6,0.000,6,0,0,0,0,0,0,0,0.50%,0.00%
2,3,Alabama,0.8,47,0.2,78,19,12,7,0.632,7,5,4,2,1,0,0,3,62.40%,19.80%
3,4,Alabama St.,0.0,92,0.0,94,1,0,1,0.000,1,0,0,0,0,0,0,0,0.00%,0.00%
4,4,Albany,-0.4,163,-0.3,162,3,0,3,0.000,3,0,0,0,0,0,0,0,0.00%,0.00%

In [24]:
# Tournament Matchups - This dataset contains the scores of previous tournament games. Every two rows is a game. For example, the first row in the 2025 YEAR has Auburn, and the second row has Alabama St. Those two teams played against each other in the First Round, and Auburn won the game 83 - 63. The following game was Louisville vs Creighton, where Creighton won the game 89 - 75. 
tournament_matchups = pd.read_csv("data/Tournament Matchups.csv")

In [25]:
# Ingestion Check
tournament_matchups.head()

   YEAR  BY YEAR NO  TEAM NO        TEAM  SEED  ROUND  CURRENT ROUND  SCORE
0  2026        2288     1207        Duke     1      1             64    NaN
1  2026        2287     1168       Siena    16     64             64    NaN
2  2026        2286     1176    Ohio St.     8      1             64    NaN
3  2026        2285     1164         TCU     9     64             64    NaN
4  2026        2284     1165  St. John's     5      1             64    NaN

In [26]:
champions = pd.read_csv("data/champions.csv")

In [27]:
champions.head()

   Year       Winner         City        State  Latitude  Longitude
0  2025      Florida  Gainesville      Florida   29.6516   -82.3248
1  2024  Connecticut    Mansfield  Connecticut   41.8084   -72.2495
2  2023  Connecticut    Mansfield  Connecticut   41.8084   -72.2495
3  2022       Kansas     Lawrence       Kansas   38.9717   -95.2353
4  2021       Baylor         Waco       Teaxas   31.5493   -97.1467

### Scraping

In [28]:
url = "https://en.wikipedia.org/wiki/List_of_NCAA_Division_I_men's_basketball_tournament_venues"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)
html = response.text

tables = pd.read_html(StringIO(html))

In [122]:
tables[0]["First Four"]

0                                         2021[Note 1]
1                                         2021[Note 1]
2    1983, 1984, 2001–2019, 2022–2025, 2026, 2027, ...
3                                           1983, 1984
Name: First Four, dtype: str

In [ ]:
# Select correct table
first_four_tables = tables[0]

# Clean columns
first_four_tables.columns = [str(col).strip() for col in first_four_tables.columns]

# Function to expand years
def expand_years(year_str):
    if pd.isna(year_str):
        return []
    
    # Remove notes like [Note 1]
    year_str = re.sub(r"\[.*?\]", "", str(year_str))
    
    parts = [p.strip() for p in year_str.split(",")]
    years = []
    
    for part in parts:
        if "–" in part:  # range (note: it's an en dash, not a hyphen)
            start, end = part.split("–")
            years.extend(range(int(start), int(end) + 1))
        elif part.isdigit():
            years.append(int(part))
    
    return years

# Apply expansion
first_four_tables["Year_List"] = first_four_tables["First Four"].apply(expand_years)

# Explode into separate rows
first_four_tables_expanded = first_four_tables.explode("Year_List")

# Rename column
first_four_tables_expanded = first_four_tables_expanded.rename(columns={"Year_List": "Year"})

# Drop original column if you want
first_four_tables_expanded = first_four_tables_expanded.drop(columns=["First Four"])

print(first_four_tables_expanded)

             City State                       Arena  No.  Year
0     Bloomington    IN  Simon Skjodt Assembly Hall    1  2021
1  West Lafayette    IN                Mackey Arena    1  2021
2          Dayton    OH                    UD Arena   25  1983
2          Dayton    OH                    UD Arena   25  1984
2          Dayton    OH                    UD Arena   25  2001
2          Dayton    OH                    UD Arena   25  2002
2          Dayton    OH                    UD Arena   25  2003
2          Dayton    OH                    UD Arena   25  2004
2          Dayton    OH                    UD Arena   25  2005
2          Dayton    OH                    UD Arena   25  2006
2          Dayton    OH                    UD Arena   25  2007
2          Dayton    OH                    UD Arena   25  2008
2          Dayton    OH                    UD Arena   25  2009
2          Dayton    OH                    UD Arena   25  2010
2          Dayton    OH                    UD Arena   25  2011
2          Dayton    OH                    UD Arena   25  2012
2          Dayton    OH                    UD Arena   25  2013
2          Dayton    OH                    UD Arena   25  2014
2          Dayton    OH                    UD Arena   25  2015
2          Dayton    OH                    UD Arena   25  2016
2          Dayton    OH                    UD Arena   25  2017
2          Dayton    OH                    UD Arena   25  2018
2          Dayton    OH                    UD Arena   25  2019
2          Dayton    OH                    UD Arena   25  2022
2          Dayton    OH                    UD Arena   25  2023
2          Dayton    OH                    UD Arena   25  2024
2          Dayton    OH                    UD Arena   25  2025
2          Dayton    OH                    UD Arena   25  2026
2          Dayton    OH                    UD Arena   25  2027
2          Dayton    OH                    UD Arena   25  2028
3    Philadelphia    PA                The Palestra    2  1983
3    Philadelphia    PA                The Palestra    2  1984

In [30]:

# Select correct table
first_second_round_locations = tables[1]

# Clean columns
first_second_round_locations.columns = [str(col).strip() for col in first_second_round_locations.columns]


# Apply expansion
first_second_round_locations["Year_List"] = first_second_round_locations["First and Second Rounds"].apply(expand_years)

# Explode into separate rows
first_second_round_locations_expanded = first_second_round_locations.explode("Year_List")

# Rename column
first_second_round_locations_expanded = first_second_round_locations_expanded.rename(columns={"Year_List": "Year"})

# Drop original column if you want
first_second_round_locations_expanded = first_second_round_locations_expanded.drop(columns=["First and Second Rounds"])

print(first_second_round_locations_expanded)

           City State           Arena  No.  Year
0    Birmingham    AL    Legacy Arena    6  1984
0    Birmingham    AL    Legacy Arena    6  1987
0    Birmingham    AL    Legacy Arena    6  2000
0    Birmingham    AL    Legacy Arena    6  2003
0    Birmingham    AL    Legacy Arena    6  2008
..          ...   ...             ...  ...   ...
167   Milwaukee    WI  Bradley Center    7  2010
167   Milwaukee    WI  Bradley Center    7  2014
167   Milwaukee    WI  Bradley Center    7  2017
168   Milwaukee    WI    Fiserv Forum    2  2022
168   Milwaukee    WI    Fiserv Forum    2  2025

[524 rows x 5 columns]

In [31]:
# Select correct table
third_fourth_round_locations = tables[2]

# Clean columns
third_fourth_round_locations.columns = [str(col).strip() for col in third_fourth_round_locations.columns]


# Apply expansion
third_fourth_round_locations["Year_List"] = third_fourth_round_locations["Regionals"].apply(expand_years)

# Explode into separate rows
third_fourth_round_locations_expanded = third_fourth_round_locations.explode("Year_List")

# Rename column
third_fourth_round_locations_expanded = third_fourth_round_locations_expanded.rename(columns={"Year_List": "Year"})

# Drop original column if you want
third_fourth_round_locations_expanded = third_fourth_round_locations_expanded.drop(columns=["Regionals"])

print(third_fourth_round_locations_expanded)

           City State                  Arena  No.  Year
0    Birmingham    AL           Legacy Arena    5  1982
0    Birmingham    AL           Legacy Arena    5  1985
0    Birmingham    AL           Legacy Arena    5  1988
0    Birmingham    AL           Legacy Arena    5  1995
0    Birmingham    AL           Legacy Arena    5  1997
..          ...   ...                    ...  ...   ...
111     Seattle    WA               Kingdome    4  1993
112  Morgantown    WV           WVU Coliseum    1  1972
113     Madison    WI  Wisconsin Field House    2  1941
113     Madison    WI  Wisconsin Field House    2  1969
114     Madison    WI            Kohl Center    1  2002

[326 rows x 5 columns]

In [32]:
# Select correct table
final_four_locations = tables[3]

# Clean columns
final_four_locations.columns = [str(col).strip() for col in final_four_locations.columns]


# Apply expansion
final_four_locations["Year_List"] = final_four_locations["Final Four"].apply(expand_years)

# Explode into separate rows
final_four_locations_expanded = final_four_locations.explode("Year_List")

# Rename column
final_four_locations_expanded = final_four_locations_expanded.rename(columns={"Year_List": "Year"})

# Drop original column if you want
final_four_locations_expanded = final_four_locations_expanded.drop(columns=["Final Four"])

print(final_four_locations_expanded)

           City State                              Arena No.  Year
0      Glendale    AZ                 State Farm Stadium   2  2017
0      Glendale    AZ                 State Farm Stadium   2  2024
1   Los Angeles    CA  Los Angeles Memorial Sports Arena   2  1968
1   Los Angeles    CA  Los Angeles Memorial Sports Arena   2  1972
2     San Diego    CA                     Pechanga Arena   1  1975
..          ...   ...                                ...  ..   ...
40      Seattle    WA             Hec Edmundson Pavilion   2  1949
40      Seattle    WA             Hec Edmundson Pavilion   2  1952
41      Seattle    WA                           Kingdome   3  1984
41      Seattle    WA                           Kingdome   3  1989
41      Seattle    WA                           Kingdome   3  1995

[92 rows x 5 columns]

## Exploratory Data Analysis

In [33]:
poll_data.head()

,YEAR,WEEK,TEAM NO,TEAM,SEED,ROUND,W,L,AP VOTES,AP RANK,RANK?
0,2026,1,1173.0,Purdue,2.0,0.0,0.0,0.0,1485.0,1.0,1
1,2026,1,1199.0,Houston,2.0,0.0,0.0,0.0,1459.0,2.0,1
2,2026,1,1206.0,Florida,1.0,0.0,0.0,0.0,1382.0,3.0,1
3,2026,1,1208.0,Connecticut,2.0,0.0,0.0,0.0,1299.0,4.0,1
4,2026,1,1165.0,St. John's,5.0,0.0,0.0,0.0,1203.0,5.0,1

In [34]:
poll_data['YEAR'].unique()

# Poll Data is GOOD

array([2026, 2025, 2024, 2023, 2022, 2021, 2019, 2018, 2017, 2016, 2015,
       2014, 2013, 2012, 2011, 2010, 2009, 2008])

In [35]:
bartt_awaynetural.head()

,YEAR,TEAM NO,TEAM ID,TEAM,SEED,ROUND,BADJ EM,BADJ O,BADJ D,BARTHAG,...,BADJT RANK,AVG HGT RANK,EFF HGT RANK,EXP RANK,TALENT RANK,FT% RANK,OP FT% RANK,PPPO RANK,PPPD RANK,ELITE SOS RANK
0,2026,1215,2,Akron,12,0,12.8,116.2,103.4,0.793,...,77,362,363,38,164,220,207,14,51,262
1,2026,1214,3,Alabama,4,0,25.4,127.5,102.1,0.928,...,3,89,76,294,8,28,67,8,209,21
2,2026,1213,8,Arizona,1,0,34.9,127.8,92.9,0.975,...,71,8,26,324,9,188,192,15,31,7
3,2026,1212,10,Arkansas,4,0,23.6,125.5,101.9,0.917,...,30,30,49,309,6,230,298,22,276,4
4,2026,1211,25,BYU,6,0,21.3,123.1,101.8,0.899,...,45,70,98,307,48,103,41,39,113,51

In [36]:
bartt_awaynetural['YEAR'].unique()

# Barttorvik Away-Neutral is GOOD

array([2026, 2025, 2024, 2023, 2022, 2021, 2019, 2018, 2017, 2016, 2015,
       2014, 2013, 2012, 2011, 2010, 2009, 2008])

In [37]:
coach_results.head()

# No Year constraint

,COACH ID,COACH,PAKE,PAKE RANK,PASE,PASE RANK,GAMES,W,L,WIN%,R64,R32,S16,E8,F4,F2,CHAMP,TOP2,F4%,CHAMP%
0,1,Tom Izzo,8.8,1,10.3,1,51,35,16,0.686,16,14,10,6,4,1,0,5,88.60%,35.50%
1,2,John Calipari,7.6,3,9.8,2,55,41,14,0.745,15,13,11,8,5,3,1,8,99.00%,75.00%
2,3,Brad Stevens,6.5,4,7.6,3,17,12,5,0.706,5,4,2,2,2,2,0,0,25.50%,3.70%
3,4,Dana Altman,6.0,5,6.5,4,26,17,9,0.654,9,9,5,2,1,0,0,1,44.20%,8.30%
4,5,John Beilein,5.5,7,6.5,5,28,19,9,0.679,9,7,5,3,2,2,0,2,65.90%,21.50%

In [38]:
conference_results.head()

# No Year Constraint

,CONF ID,CONF,PAKE,PAKE RANK,PASE,PASE RANK,GAMES,W,L,WIN%,R64,R32,S16,E8,F4,F2,CHAMP,TOP2,CHAMP%
0,2,ACC,15.2,1,10.2,1,255,161,94,0.631,99,66,44,26,13,7,5,28,96.40%
1,14,Horz,5.9,4,7.9,2,31,13,18,0.419,18,5,2,2,2,2,0,0,3.70%
2,28,SEC,6.6,2,7.5,3,228,134,94,0.588,96,59,37,23,10,3,2,18,92.30%
3,24,P12,6.1,3,7.3,4,146,83,63,0.568,63,44,27,9,3,0,0,9,66.50%
4,6,B10,2.2,8,5.9,5,271,159,112,0.587,112,84,43,17,10,5,0,21,93.00%

In [39]:
conference_stats.head()

,YEAR,CONF ID,CONF,BADJ EM,BADJ O,BADJ D,BARTHAG,G,W,L,...,AVG HGT,EFF HGT,EXP,TALENT,FT%,OP FT%,PPPO,PPPD,ELITE SOS,WAB
0,2026,1,A10,4.2,109.9,105.7,0.610,222,94,128,...,77.320,80.480,2.050,17.554,71.4,71.7,1.055,1.095,26.390,-3.50
1,2026,2,ACC,16.6,118.2,101.6,0.851,271,122,149,...,78.069,81.107,1.798,55.261,71.3,73.7,1.094,1.111,47.966,0.29
2,2026,3,AE,-15.6,99.5,115.1,0.158,162,42,120,...,76.993,80.087,1.703,6.229,69.6,71.6,0.991,1.128,13.937,-10.00
3,2026,4,Amer,2.0,109.4,107.4,0.553,210,94,116,...,77.342,80.448,1.951,24.405,72.4,72.4,1.059,1.106,23.642,-3.90
4,2026,5,ASun,-10.1,104.9,115.0,0.258,219,63,156,...,77.215,80.117,1.743,7.524,71.8,73.0,1.055,1.176,18.774,-8.70

In [40]:
conference_stats['YEAR'].unique()

# Conference Stats Away Neutral is GOOD

array([2026, 2025, 2024, 2023, 2022, 2021, 2019, 2018, 2017, 2016, 2015,
       2014, 2013, 2012, 2011, 2010, 2009, 2008])

In [41]:
heat_check_ratings.head()

,YEAR,TEAM NO,TEAM,SEED,ROUND,EASY DRAW,TOUGH DRAW,DARK HORSE,UPSET ALERT,CINDERELLA
0,2026,1188,Louisville,6,0,False,False,True,False,False
1,2026,1163,Tennessee,6,0,False,False,True,False,False
2,2025,1135,Connecticut,8,32,False,False,True,False,False
3,2025,1103,Oklahoma,9,64,False,True,False,False,False
4,2025,1115,Memphis,5,64,False,True,False,True,False

In [42]:
heat_check_ratings['YEAR'].unique()

# Heat Check Ratings is NOT Good

array([2026, 2025, 2024, 2023, 2022, 2021, 2019, 2018, 2017, 2016, 2015,
       2014, 2013])

In [43]:
heat_check_index.head()

,YEAR,TEAM NO,TEAM,SEED,ROUND,POWER,PATH,DRAW,WINS,POOL VALUE,POOL S-RANK,NCAA S-RANK,VAL Z-SCORE,POWER-PATH
0,2026,1215,Akron,12,0,63.2,83.4,NaN,NaN,2.4,47,48,NaN,-20.2
1,2026,1214,Alabama,4,0,84.4,72.4,NaN,NaN,32.3,13,14,NaN,12.0
2,2026,1213,Arizona,1,0,94.0,66.1,NaN,NaN,84.6,2,2,NaN,27.9
3,2026,1212,Arkansas,4,0,82.5,67.8,NaN,NaN,45.9,10,16,NaN,14.7
4,2026,1211,BYU,6,0,78.3,72.9,NaN,NaN,16.7,23,24,NaN,5.4

In [44]:
heat_check_index['YEAR'].unique()

# Heat Check Tournament Index is NOT Good

array([2026, 2025, 2024, 2023, 2022, 2021, 2019, 2018, 2017, 2016, 2015,
       2014, 2013])

In [45]:
resumes.head()

,YEAR,TEAM NO,TEAM,SEED,ROUND,NET RPI,RESUME,WAB RANK,ELO,B POWER,Q1 W,Q2 W,Q1 PLUS Q2 W,Q3 Q4 L,PLUS 500,R SCORE,BID TYPE
0,2026,1215,Akron,12,0,53,114,53,27,70.7,0,0,0,1,23,0.91,Auto
1,2026,1214,Alabama,4,0,18,14,14,23,16.7,7,9,16,0,15,99.45,At-Large
2,2026,1213,Arizona,1,0,3,3,3,2,3.0,16,8,24,0,31,99.98,Auto
3,2026,1212,Arkansas,4,0,16,17,15,11,19.0,8,8,16,0,19,99.51,Auto
4,2026,1211,BYU,6,0,22,21,22,38,24.7,7,8,15,0,12,98.40,At-Large

In [46]:
resumes['YEAR'].unique()

# Reumes is Good

array([2026, 2025, 2024, 2023, 2022, 2021, 2019, 2018, 2017, 2016, 2015,
       2014, 2013, 2012, 2011, 2010, 2009, 2008])

In [47]:
seed_results.head()

# No Year Constraint

,SEED,PAKE,PAKE RANK,PASE,PASE RANK,GAMES,W,L,WIN%,R64,R32,S16,E8,F4,F2,CHAMP,TOP2,CHAMP%
0,11,14.2,2,14.8,1,127,59,68,0.465,68,33,16,6,4,0,0,0,11.80%
1,15,3.8,5,5.2,2,80,12,68,0.150,68,7,4,1,0,0,0,0,0.00%
2,3,5.9,3,4.0,3,196,129,67,0.658,68,60,40,20,5,3,1,0,80.70%
3,4,2.5,6,3.8,4,177,110,67,0.621,68,53,37,11,6,2,1,0,75.80%
4,8,-0.3,8,3.0,5,119,51,68,0.429,68,35,7,3,3,3,0,0,16.30%

In [48]:
shooting_splits.head()

,YEAR,TEAM NO,TEAM ID,TEAM,CONF,DUNKS FG%,DUNKS SHARE,DUNKS FG%D,DUNKS D SHARE,CLOSE TWOS FG%,...,CLOSE TWOS FG%D RANK,CLOSE TWOS D SHARE RANK,FARTHER TWOS FG% RANK,FARTHER TWOS SHARE RANK,FARTHER TWOS FG%D RANK,FARTHER TWOS D SHARE RANK,THREES FG% RANK,THREES SHARE RANK,THREES FG%D RANK,THREES D SHARE RANK
0,2026,1215,2,Akron,MAC,93.1,7.9,87.0,4.2,65.0,...,67,159,22,57,50,295,14,65,256,305
1,2026,1214,3,Alabama,SEC,85.9,10.1,92.7,7.6,61.4,...,86,152,17,14,145,34,72,1,160,52
2,2026,1213,8,Arizona,B12,93.4,9.0,91.4,6.1,64.1,...,19,8,31,345,86,2,62,363,46,109
3,2026,1212,10,Arkansas,SEC,92.0,15.4,87.1,9.8,67.1,...,291,224,307,227,177,174,8,311,56,144
4,2026,1211,25,BYU,B12,84.2,10.4,81.2,8.0,66.9,...,296,14,44,292,153,8,130,174,266,177

In [49]:
shooting_splits['YEAR'].unique()

# Shooting Split is NOT Good

array([2026, 2025, 2024, 2023, 2022, 2021, 2019, 2018, 2017, 2016, 2015,
       2014, 2013, 2012, 2011, 2010])

In [50]:
team_results.head()

# No Year Constraint

,TEAM ID,TEAM,PAKE,PAKE RANK,PASE,PASE RANK,GAMES,W,L,WIN%,R64,R32,S16,E8,F4,F2,CHAMP,TOP2,F4%,CHAMP%
0,1,Abilene Christian,0.7,53,0.7,55,3,1,2,0.333,2,1,0,0,0,0,0,0,0.10%,0.00%
1,2,Akron,-1.2,201,-1.5,208,6,0,6,0.000,6,0,0,0,0,0,0,0,0.50%,0.00%
2,3,Alabama,0.8,47,0.2,78,19,12,7,0.632,7,5,4,2,1,0,0,3,62.40%,19.80%
3,4,Alabama St.,0.0,92,0.0,94,1,0,1,0.000,1,0,0,0,0,0,0,0,0.00%,0.00%
4,4,Albany,-0.4,163,-0.3,162,3,0,3,0.000,3,0,0,0,0,0,0,0,0.00%,0.00%

In [51]:
tournament_matchups.head()

   YEAR  BY YEAR NO  TEAM NO        TEAM  SEED  ROUND  CURRENT ROUND  SCORE
0  2026        2288     1207        Duke     1      1             64    NaN
1  2026        2287     1168       Siena    16     64             64    NaN
2  2026        2286     1176    Ohio St.     8      1             64    NaN
3  2026        2285     1164         TCU     9     64             64    NaN
4  2026        2284     1165  St. John's     5      1             64    NaN

In [52]:
tournament_matchups['YEAR'].unique()

# Tournament Matchups is GOOD

array([2026, 2025, 2024, 2023, 2022, 2021, 2019, 2018, 2017, 2016, 2015,
       2014, 2013, 2012, 2011, 2010, 2009, 2008])

After looking through the dates in each of the CSV files. The date range I am going to use is 2010 to 2025. This should give me enough data to work with and draw conclusions from. I originally wanted to use from 2008, but I thoguht shooting splits would be important, but that CSV file only went to 2010 which is why it is my lower limit. The following CSV files are the ones I will be using:

AP Poll Data.csv,
Barttorvik Away-Neutral.csv,
Resumes.csv,
Seed Results.csv,
Shooting Splits.csv,
Team Results.csv

In [53]:
poll_data.head()

,YEAR,WEEK,TEAM NO,TEAM,SEED,ROUND,W,L,AP VOTES,AP RANK,RANK?
0,2026,1,1173.0,Purdue,2.0,0.0,0.0,0.0,1485.0,1.0,1
1,2026,1,1199.0,Houston,2.0,0.0,0.0,0.0,1459.0,2.0,1
2,2026,1,1206.0,Florida,1.0,0.0,0.0,0.0,1382.0,3.0,1
3,2026,1,1208.0,Connecticut,2.0,0.0,0.0,0.0,1299.0,4.0,1
4,2026,1,1165.0,St. John's,5.0,0.0,0.0,0.0,1203.0,5.0,1

In [54]:
poll_data.isnull().sum()

YEAR           0
WEEK           0
TEAM NO     3305
TEAM           0
SEED        3305
ROUND       3305
W           3731
L           3731
AP VOTES       2
AP RANK        2
RANK?          0
dtype: int64

In [55]:
bartt_awaynetural.isnull().sum()

YEAR              0
TEAM NO           0
TEAM ID           0
TEAM              0
SEED              0
                 ..
FT% RANK          0
OP FT% RANK       0
PPPO RANK         0
PPPD RANK         0
ELITE SOS RANK    0
Length: 85, dtype: int64

In [56]:
resumes.isnull().sum()

YEAR            0
TEAM NO         0
TEAM            0
SEED            0
ROUND           0
NET RPI         0
RESUME          0
WAB RANK        0
ELO             0
B POWER         0
Q1 W            0
Q2 W            0
Q1 PLUS Q2 W    0
Q3 Q4 L         0
PLUS 500        0
R SCORE         0
BID TYPE        1
dtype: int64

In [57]:
seed_results.isnull().sum()

SEED         0
PAKE         0
PAKE RANK    0
PASE         0
PASE RANK    0
GAMES        0
W            0
L            0
WIN%         0
R64          0
R32          0
S16          0
E8           0
F4           0
F2           0
CHAMP        0
TOP2         0
CHAMP%       0
dtype: int64

In [58]:
shooting_splits.isnull().sum()

YEAR                         0
TEAM NO                      0
TEAM ID                      0
TEAM                         0
CONF                         0
DUNKS FG%                    0
DUNKS SHARE                  0
DUNKS FG%D                   0
DUNKS D SHARE                0
CLOSE TWOS FG%               0
CLOSE TWOS SHARE             0
CLOSE TWOS FG%D              0
CLOSE TWOS D SHARE           0
FARTHER TWOS FG%             0
FARTHER TWOS SHARE           0
FARTHER TWOS FG%D            0
FARTHER TWOS D SHARE         0
THREES FG%                   0
THREES SHARE                 0
THREES FG%D                  0
THREES D SHARE               0
DUNKS FG% RANK               0
DUNKS SHARE RANK             0
DUNKS FG%D RANK              0
DUNKS D SHARE RANK           0
CLOSE TWOS FG% RANK          0
CLOSE TWOS SHARE RANK        0
CLOSE TWOS FG%D RANK         0
CLOSE TWOS D SHARE RANK      0
FARTHER TWOS FG% RANK        0
FARTHER TWOS SHARE RANK      0
FARTHER TWOS FG%D RANK       0
FARTHER TWOS D SHARE RANK    0
THREES FG% RANK              0
THREES SHARE RANK            0
THREES FG%D RANK             0
THREES D SHARE RANK          0
dtype: int64

In [59]:
team_results.isnull().sum()

TEAM ID      0
TEAM         0
PAKE         0
PAKE RANK    0
PASE         0
PASE RANK    0
GAMES        0
W            0
L            0
WIN%         0
R64          0
R32          0
S16          0
E8           0
F4           0
F2           0
CHAMP        0
TOP2         0
F4%          0
CHAMP%       0
dtype: int64

In [60]:
first_four_tables_expanded.isnull().sum()

City     0
State    0
Arena    0
No.      0
Year     0
dtype: int64

In [61]:
first_four_tables_expanded['Year'].unique()

array([2021, 1983, 1984, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008,
       2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019,
       2022, 2023, 2024, 2025, 2026, 2027, 2028], dtype=object)

In [62]:
first_second_round_locations_expanded.isnull().sum()

City     0
State    0
Arena    0
No.      0
Year     0
dtype: int64

In [63]:
first_second_round_locations_expanded['Year'].unique()

array([1984, 1987, 2000, 2003, 2008, 2023, 2028, 1975, 1981, 1976, 1978,
       1980, 1992, 1996, 1977, 1979, 1989, 1991, 1993, 1997, 2005, 2011,
       1958, 1955, 1986, 1990, 1988, 1953, 1994, 1998, 2002, 2007, 2017,
       2027, 2001, 2006, 2014, 2018, 2022, 2026, 2010, 2013, 2019, 1999,
       2004, 2016, 2025, 1967, 1983, 1985, 2015, 2009, 1995, 1957, 1972,
       1974, 1969, 1960, 1963, 1964, 1954, 2021, 1956, 1982, 2024, 1971,
       1966, 1973, 1965, 1959, 1962, 1961, 2012, 1968, 1951, 1970],
      dtype=object)

In [64]:
third_fourth_round_locations_expanded.isnull().sum()

City     0
State    0
Arena    0
No.      0
Year     0
dtype: int64

In [65]:
third_fourth_round_locations_expanded['Year'].unique()

array([1982, 1985, 1988, 1995, 1997, 1974, 2009, 1999, 2004, 2008, 2012,
       1980, 1998, 2001, 2003, 2011, 2014, 2016, 2019, 1994, 1966, 1969,
       1973, 1976, 1984, 2013, 2015, 2018, 2024, 2027, 1990, 2006, 1939,
       1958, 1959, 2022, 2025, 2028, 2002, 2007, 2017, 2026, 1989, 1996,
       1971, 1981, 1986, 2005, 1952, 1953, 1955, 1967, 1940, 2021, 1979,
       1972, 1954, 1956, 1962, 1961, 1963, 1970, 1978, 1960, 1965, 1964,
       1968, 1957, 1977, 1992, 1987, 2023, 1942, 2000, 1991, 1941, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1983, 1993, 2010,
       1975], dtype=object)

In [66]:
final_four_locations_expanded.isnull().sum()

City     0
State    0
Arena    0
No.      0
Year     0
dtype: int64

In [67]:
final_four_locations_expanded['Year'].unique()

array([2017, 2024, 1968, 1972, 1975, 1960, 1990, 1999, 1977, 2002, 2007,
       2013, 2031, 1939, 1956, 1980, 1991, 1997, 2000, 2006, 2010, 2015,
       2021, 2026, 2029, 1985, 1958, 1959, 1962, 1963, 1967, 1969, 1982,
       1987, 1993, 2003, 2012, 2022, 1966, 1970, 2009, 2027, 1951, 1992,
       2001, 2019, 1940, 1941, 1942, 1953, 1954, 1955, 1957, 1961, 1964,
       1988, 1973, 1978, 2005, 1996, 1983, 1943, 1944, 1945, 1946, 1947,
       1948, 1950, 1994, 1974, 2028, 1965, 1976, 1981, 2014, 2030, 1986,
       1971, 2011, 2016, 2023, 1998, 2004, 2008, 2018, 2025, 1979, 1949,
       1952, 1984, 1989, 1995], dtype=object)

In [68]:
team_results.head()

,TEAM ID,TEAM,PAKE,PAKE RANK,PASE,PASE RANK,GAMES,W,L,WIN%,R64,R32,S16,E8,F4,F2,CHAMP,TOP2,F4%,CHAMP%
0,1,Abilene Christian,0.7,53,0.7,55,3,1,2,0.333,2,1,0,0,0,0,0,0,0.10%,0.00%
1,2,Akron,-1.2,201,-1.5,208,6,0,6,0.000,6,0,0,0,0,0,0,0,0.50%,0.00%
2,3,Alabama,0.8,47,0.2,78,19,12,7,0.632,7,5,4,2,1,0,0,3,62.40%,19.80%
3,4,Alabama St.,0.0,92,0.0,94,1,0,1,0.000,1,0,0,0,0,0,0,0,0.00%,0.00%
4,4,Albany,-0.4,163,-0.3,162,3,0,3,0.000,3,0,0,0,0,0,0,0,0.00%,0.00%

In [69]:
team_results.groupby('TEAM')['CHAMP'].sum().sort_values(ascending=False)

TEAM
Connecticut       4
Villanova         2
North Carolina    2
Duke              2
Kansas            2
                 ..
LIU Brooklyn      0
LSU               0
La Salle          0
Lafayette         0
Yale              0
Name: CHAMP, Length: 248, dtype: int64

## Data Cleaning

In [70]:
poll_data_nulls = poll_data.dropna(subset=['TEAM NO'])

# Removes teams that were not in the tournament for the given year

In [71]:
clean_poll_data = poll_data_nulls.drop('W', axis = 1)

In [72]:
clean_poll_data = clean_poll_data.drop('L', axis = 1)

In [73]:
clean_poll_data['TEAM NO'] = clean_poll_data['TEAM NO'].astype(int)

In [74]:
clean_poll_data = clean_poll_data[clean_poll_data['YEAR'].between(2010, 2025)]

In [75]:
clean_poll_data['YEAR'].unique()

array([2025, 2024, 2023, 2022, 2021, 2019, 2018, 2017, 2016, 2015, 2014,
       2013, 2012, 2011, 2010])

In [76]:
clean_poll_data.head()

     YEAR  WEEK  TEAM NO         TEAM  SEED  ROUND  AP VOTES  AP RANK  RANK?
823  2025     1     1123       Kansas   7.0   64.0    1449.0      1.0      1
824  2025     1     1146      Alabama   2.0    8.0    1428.0      2.0      1
825  2025     1     1135  Connecticut   8.0   32.0    1345.0      3.0      1
826  2025     1     1126      Houston   1.0    2.0    1343.0      4.0      1
827  2025     1     1124     Iowa St.   3.0   32.0    1177.0      5.0      1

In [77]:
clean_poll_data.isnull().sum()

YEAR        0
WEEK        0
TEAM NO     0
TEAM        0
SEED        0
ROUND       0
AP VOTES    1
AP RANK     1
RANK?       0
dtype: int64

In [78]:
clean_bartt_awaynetural = bartt_awaynetural[bartt_awaynetural["YEAR"].between(2010, 2025)]

In [79]:
clean_bartt_awaynetural['YEAR'].unique()

array([2025, 2024, 2023, 2022, 2021, 2019, 2018, 2017, 2016, 2015, 2014,
       2013, 2012, 2011, 2010])

In [80]:
clean_bartt_awaynetural.head()

,YEAR,TEAM NO,TEAM ID,TEAM,SEED,ROUND,BADJ EM,BADJ O,BADJ D,BARTHAG,...,BADJT RANK,AVG HGT RANK,EFF HGT RANK,EXP RANK,TALENT RANK,FT% RANK,OP FT% RANK,PPPO RANK,PPPD RANK,ELITE SOS RANK
68,2025,1147,2,Akron,13,64,4.7,108.6,103.9,0.625,...,10,361,364,73,149,48,143,55,54,307
69,2025,1146,3,Alabama,2,8,31.0,130.5,99.5,0.958,...,3,57,4,261,32,201,75,5,253,4
70,2025,1145,4,Alabama St.,16,64,-7.2,100.5,107.7,0.311,...,136,285,239,83,251,270,46,236,77,263
71,2025,1144,6,American,16,68,-8.7,102.0,110.7,0.281,...,343,303,248,181,364,40,165,222,244,303
72,2025,1143,8,Arizona,4,16,24.4,120.7,96.3,0.931,...,42,74,129,225,16,5,223,63,97,10

In [81]:
clean_resumes = resumes[resumes['YEAR'].between(2010, 2025)]

In [82]:
clean_resumes['YEAR'].unique()

array([2025, 2024, 2023, 2022, 2021, 2019, 2018, 2017, 2016, 2015, 2014,
       2013, 2012, 2011, 2010])

In [83]:
clean_resumes.head()

,YEAR,TEAM NO,TEAM,SEED,ROUND,NET RPI,RESUME,WAB RANK,ELO,B POWER,Q1 W,Q2 W,Q1 PLUS Q2 W,Q3 Q4 L,PLUS 500,R SCORE,BID TYPE
68,2025,1147,Akron,13,64,91,112,65,45,104.0,0,1,1,3,21,0.02,Auto
69,2025,1146,Alabama,2,8,6,2,4,8,5.7,11,8,19,0,18,99.92,At-Large
70,2025,1145,Alabama St.,16,64,274,265,200,196,274.3,0,0,0,9,4,0.00,Auto
71,2025,1144,American,16,68,225,225,164,163,236.0,0,0,0,8,10,0.00,Auto
72,2025,1143,Arizona,4,16,12,10,15,25,10.7,9,5,14,0,11,99.69,At-Large

In [84]:
seed_results.head()

,SEED,PAKE,PAKE RANK,PASE,PASE RANK,GAMES,W,L,WIN%,R64,R32,S16,E8,F4,F2,CHAMP,TOP2,CHAMP%
0,11,14.2,2,14.8,1,127,59,68,0.465,68,33,16,6,4,0,0,0,11.80%
1,15,3.8,5,5.2,2,80,12,68,0.150,68,7,4,1,0,0,0,0,0.00%
2,3,5.9,3,4.0,3,196,129,67,0.658,68,60,40,20,5,3,1,0,80.70%
3,4,2.5,6,3.8,4,177,110,67,0.621,68,53,37,11,6,2,1,0,75.80%
4,8,-0.3,8,3.0,5,119,51,68,0.429,68,35,7,3,3,3,0,0,16.30%

In [85]:
# Seed Results does not need cleaned for 'YEAR'

In [86]:
team_results.head()

,TEAM ID,TEAM,PAKE,PAKE RANK,PASE,PASE RANK,GAMES,W,L,WIN%,R64,R32,S16,E8,F4,F2,CHAMP,TOP2,F4%,CHAMP%
0,1,Abilene Christian,0.7,53,0.7,55,3,1,2,0.333,2,1,0,0,0,0,0,0,0.10%,0.00%
1,2,Akron,-1.2,201,-1.5,208,6,0,6,0.000,6,0,0,0,0,0,0,0,0.50%,0.00%
2,3,Alabama,0.8,47,0.2,78,19,12,7,0.632,7,5,4,2,1,0,0,3,62.40%,19.80%
3,4,Alabama St.,0.0,92,0.0,94,1,0,1,0.000,1,0,0,0,0,0,0,0,0.00%,0.00%
4,4,Albany,-0.4,163,-0.3,162,3,0,3,0.000,3,0,0,0,0,0,0,0,0.00%,0.00%

In [87]:
# Team Results does not need cleaned for 'YEAR'

In [88]:
shooting_splits.head()

,YEAR,TEAM NO,TEAM ID,TEAM,CONF,DUNKS FG%,DUNKS SHARE,DUNKS FG%D,DUNKS D SHARE,CLOSE TWOS FG%,...,CLOSE TWOS FG%D RANK,CLOSE TWOS D SHARE RANK,FARTHER TWOS FG% RANK,FARTHER TWOS SHARE RANK,FARTHER TWOS FG%D RANK,FARTHER TWOS D SHARE RANK,THREES FG% RANK,THREES SHARE RANK,THREES FG%D RANK,THREES D SHARE RANK
0,2026,1215,2,Akron,MAC,93.1,7.9,87.0,4.2,65.0,...,67,159,22,57,50,295,14,65,256,305
1,2026,1214,3,Alabama,SEC,85.9,10.1,92.7,7.6,61.4,...,86,152,17,14,145,34,72,1,160,52
2,2026,1213,8,Arizona,B12,93.4,9.0,91.4,6.1,64.1,...,19,8,31,345,86,2,62,363,46,109
3,2026,1212,10,Arkansas,SEC,92.0,15.4,87.1,9.8,67.1,...,291,224,307,227,177,174,8,311,56,144
4,2026,1211,25,BYU,B12,84.2,10.4,81.2,8.0,66.9,...,296,14,44,292,153,8,130,174,266,177

In [89]:
clean_shooting_splits = shooting_splits[shooting_splits['YEAR'].between(2010, 2025)]

In [90]:
clean_shooting_splits['YEAR'].unique()

array([2025, 2024, 2023, 2022, 2021, 2019, 2018, 2017, 2016, 2015, 2014,
       2013, 2012, 2011, 2010])

In [91]:
clean_shooting_splits.head()

,YEAR,TEAM NO,TEAM ID,TEAM,CONF,DUNKS FG%,DUNKS SHARE,DUNKS FG%D,DUNKS D SHARE,CLOSE TWOS FG%,...,CLOSE TWOS FG%D RANK,CLOSE TWOS D SHARE RANK,FARTHER TWOS FG% RANK,FARTHER TWOS SHARE RANK,FARTHER TWOS FG%D RANK,FARTHER TWOS D SHARE RANK,THREES FG% RANK,THREES SHARE RANK,THREES FG%D RANK,THREES D SHARE RANK
68,2025,1147,2,Akron,MAC,85.9,7.0,80.0,3.7,61.8,...,24,66,22,56,61,8,20,14,28,26
69,2025,1146,3,Alabama,SEC,90.4,13.7,88.7,7.9,62.4,...,35,30,1,66,53,60,34,12,13,9
70,2025,1145,4,Alabama St.,SWAC,77.0,5.2,81.0,5.6,53.1,...,41,50,67,39,41,21,56,20,49,36
71,2025,1144,6,American,Pat,76.2,2.2,94.9,3.6,58.5,...,62,58,37,37,43,36,32,16,52,13
72,2025,1143,8,Arizona,B12,95.3,9.5,85.7,6.9,65.9,...,28,6,46,19,47,54,60,57,52,48

In [92]:
clean_first_four_locations = first_four_tables_expanded[first_four_tables_expanded['Year'].between(2010, 2025)]

In [93]:
clean_first_four_locations['Year'].unique()

array([2021, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019,
       2022, 2023, 2024, 2025], dtype=object)

In [94]:
clean_first_second_round_locations = first_second_round_locations_expanded[first_second_round_locations_expanded['Year'].between(2010, 2025)]

In [95]:
clean_first_second_round_locations['Year'].unique()

array([2023, 2011, 2017, 2014, 2018, 2022, 2010, 2013, 2019, 2016, 2025,
       2015, 2021, 2024, 2012], dtype=object)

In [96]:
clean_third_fourth_round_locations = third_fourth_round_locations_expanded[third_fourth_round_locations_expanded['Year'].between(2010, 2025)]

In [97]:
clean_third_fourth_round_locations['Year'].unique()

array([2012, 2011, 2014, 2016, 2019, 2013, 2015, 2018, 2024, 2022, 2025,
       2017, 2021, 2023, 2010], dtype=object)

In [98]:
clean_final_four_locations = final_four_locations_expanded[final_four_locations_expanded['Year'].between(2010, 2025)]

In [99]:
clean_final_four_locations['Year'].unique()

array([2017, 2024, 2013, 2010, 2015, 2021, 2012, 2022, 2019, 2014, 2011,
       2016, 2023, 2018, 2025], dtype=object)

In [100]:
arena_coords = {
    "State Farm Stadium": {"latitude": 33.5276, "longitude": -112.2626},
    "Georgia Dome": {"latitude": 33.7573, "longitude": -84.4008},
    "Lucas Oil Stadium": {"latitude": 39.7601, "longitude": -86.1639},
    "Caesars Superdome": {"latitude": 29.9511, "longitude": -90.0812},
    "U.S. Bank Stadium": {"latitude": 44.9738, "longitude": -93.2575},
    "AT&T Stadium": {"latitude": 32.7473, "longitude": -97.0945},
    "NRG Stadium": {"latitude": 29.6847, "longitude": -95.4107},
    "Alamodome": {"latitude": 29.4169, "longitude": -98.4785}
}

clean_final_four_locations["Latitude"] = clean_final_four_locations["Arena"].map(
    lambda x: arena_coords.get(x, {}).get("latitude")
)

clean_final_four_locations["Longitude"] = clean_final_four_locations["Arena"].map(
    lambda x: arena_coords.get(x, {}).get("longitude"))

In [101]:
clean_final_four_locations.head()

            City State               Arena No.  Year  Latitude  Longitude
0       Glendale    AZ  State Farm Stadium   2  2017   33.5276  -112.2626
0       Glendale    AZ  State Farm Stadium   2  2024   33.5276  -112.2626
7        Atlanta    GA        Georgia Dome   3  2013   33.7573   -84.4008
13  Indianapolis    IN   Lucas Oil Stadium   4  2010   39.7601   -86.1639
13  Indianapolis    IN   Lucas Oil Stadium   4  2015   39.7601   -86.1639

## Writing to Database

In [102]:
from sqlalchemy import create_engine

PG_URL = 'postgresql+psycopg2://postgres:postgres@localhost:5430/postgres'
engine = create_engine(PG_URL)
print('Database:', PG_URL)

Database: postgresql+psycopg2://postgres:postgres@localhost:5430/postgres

In [107]:
# Writing Clean_Poll_Data

engine = create_engine(PG_URL)
clean_poll_data.to_sql('poll_data', engine, if_exists='replace', index=False)

812

In [108]:
# Writing Barttorvik Away-Neutral

clean_bartt_awaynetural.to_sql('bartt_away_neutral', engine, if_exists='replace', index=False)

249

In [109]:
# Writing Resumes

clean_resumes.to_sql('resumes', engine, if_exists='replace', index=False)

17

In [110]:
# Writing Seed Results

seed_results.to_sql('seed_results', engine, if_exists='replace', index=False)

16

In [111]:
# Writing Shooting Splits

clean_shooting_splits.to_sql('shooting_splits', engine, if_exists='replace', index=False)

134

In [112]:
# Writing Team Results

team_results.to_sql('team_results', engine, if_exists='replace', index=False)

248

In [114]:
# Writing First Four Locations

clean_first_four_locations.to_sql('first_four_locations', engine, if_exists='replace', index=False)

16

In [115]:
# Writing First and Second Round Locations

clean_first_second_round_locations.to_sql('first_second_round_locations', engine, if_exists='replace', index=False)

118

In [116]:
# Writing Third and Fourth Round Locations

clean_third_fourth_round_locations.to_sql('third_fourth_round_locations', engine, if_exists='replace', index=False)

59

In [117]:
# Writing Final Four Locations

clean_final_four_locations.to_sql('final_four_locations', engine, if_exists='replace', index=False)

15

In [118]:
champions.to_sql('champions', engine, if_exists='replace', index=False)

16

In [119]:
# Closing Engine Connection
engine.dispose()